name: Helm Deploy
description: Updates YAML file in BitBucket by updating a jsonpath entry with a new value
inputs:
  file:
    description: For example 'ken-test/applications/default/security/ussd/values.yaml'
    required: true
  value:
    description: For example `v1.2.3`
    required: true
  username:
    description: Username for login to Git URL
    required: true
    default: carepaybot
  password:
    required: true
  jsonpath:
    required: true
    default: $.microservice.image
  workspace:
    description: Bitbucket workspace slug
    required: true
    default: carepaydev
  repository:
    description: Bitbucket repository slug
    required: true
    default: central-configs
runs:
  using: "node24"
  main: "dist/index.js"
