name: Helm Deploy
description: Greet someone and record the time
inputs:
  app:
    description: For example `health-hub-web`
    required: true
    default: ${{ vars.APP }}
  namespace:
    description: For example 'default'
    required: true
    default: ${{ vars.NAMESPACE || 'default' }}
  team:
    description: For example 'health-hub'
    required: true
    default: ${{ vars.TEAM }}
  country:
    description: For example `ae`
    required: true
  stage:
    description: For example `acc`
    required: true
  tag:
    description: For example `v1.2.3`
    required: true
    default: ${{ startsWith(github.ref,'refs/tags') && github.ref_name || github.sha }}
  username:
    description: Username for login to Git URL
    required: true
    default: carepaybot
  password:
    required: true
    default: ${{ secrets.BITBUCKET_APP_PASSWORD }}
  jsonpath:
    required: true
    default: $.microservice.image
  workspace:
    description: Bitbucket workspace slug
    required: true
    default: carepaydev
  repository:
    description: Bitbucket repository slug
    required: true
    default: central-configs
runs:
  using: "node24"
  main: "dist/index.js"
